---
- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: localhost
  become: yes
  tasks:
    - name: Update cache
      apt: update_cache=yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: /workspaces/ensf400-lab5-ansible/assignment2/nginx.conf
        dest: /etc/nginx/sites-available/loadbalancer.conf
        owner: root
        group: root
        mode: "0644"
      become: yes
    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/loadbalancer.conf
        dest: /etc/nginx/sites-enabled/loadbalancer.conf
        state: link
      become: yes
    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted
