version: "3.7"

services:
  loadbalancer:
    build:
      context: /workspaces/ensf400-lab5-ansible/assignment2/
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - /workspaces/ensf400-lab5-ansible/assignment2/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - managedhost-app-1
      - managedhost-app-2
      - managedhost-app-3

  managedhost-app-1:
    build:
      context: /workspaces/ensf400-lab5-ansible/managed-host/alpine/app1
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - /workspaces/ensf400-lab5-ansible/secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3000:3000"
      - "2223:2223"

  managedhost-app-2:
    build:
      context: /workspaces/ensf400-lab5-ansible/managed-host/alpine/app2
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - /workspaces/ensf400-lab5-ansible/secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3001:3000"
      - "2224:2224"

  managedhost-app-3:
    build:
      context: /workspaces/ensf400-lab5-ansible/managed-host/alpine/app3
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - /workspaces/ensf400-lab5-ansible/secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3002:3000"
      - "2225:2225"

networks:
  app-network:
